version: '3.8'

services:
  # Database Services
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: ${DB_NAME:-digidig_production}
      POSTGRES_USER: ${DB_USER:-prod_user}
      POSTGRES_PASSWORD: ${DB_PASS:-production_secure_password}
    volumes:
      - postgres_production_data:/var/lib/postgresql/data
      - ./backups:/backups
    networks:
      - digidig-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-prod_user}"]
      interval: 30s
      timeout: 10s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  mongodb:
    image: mongo:7
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER:-prod_mongo}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS:-production_mongo_secure}
    volumes:
      - mongodb_production_data:/data/db
      - ./backups:/backups
    networks:
      - digidig-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Application Services
  identity:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER:-digidig}/digidig-identity:${IMAGE_TAG:-latest}
    environment:
      - DIGIDIG_ENV=production
      - DB_HOST=postgres
      - DB_NAME=${DB_NAME:-digidig_production}
      - DB_USER=${DB_USER:-prod_user}
      - DB_PASS=${DB_PASS:-production_secure_password}
      - JWT_SECRET=${JWT_SECRET}  # Required in production
      - ADMIN_EMAIL=${ADMIN_EMAIL}  # Required in production
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}  # Required in production
    ports:
      - "8001:8001"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - digidig-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  storage:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER:-digidig}/digidig-storage:${IMAGE_TAG:-latest}
    environment:
      - DIGIDIG_ENV=production
      - MONGO_HOST=mongodb
      - MONGO_USER=${MONGO_USER:-prod_mongo}
      - MONGO_PASS=${MONGO_PASS:-production_mongo_secure}
      - IDENTITY_URL=http://identity:8001
    ports:
      - "8002:8002"
    depends_on:
      mongodb:
        condition: service_healthy
      identity:
        condition: service_healthy
    networks:
      - digidig-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/api/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  smtp:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER:-digidig}/digidig-smtp:${IMAGE_TAG:-latest}
    environment:
      - DIGIDIG_ENV=production
      - IDENTITY_URL=http://identity:8001
      - STORAGE_URL=http://storage:8002
      - SMTP_HOST=${SMTP_HOST}  # Required in production
      - SMTP_USERNAME=${SMTP_USERNAME}  # Required in production
      - SMTP_PASSWORD=${SMTP_PASSWORD}  # Required in production
      - SMTP_PORT=${SMTP_PORT:-587}
      - SMTP_USE_TLS=${SMTP_USE_TLS:-true}
    ports:
      - "8000:8000"
    depends_on:
      identity:
        condition: service_healthy
      storage:
        condition: service_healthy
    networks:
      - digidig-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  imap:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER:-digidig}/digidig-imap:${IMAGE_TAG:-latest}
    environment:
      - DIGIDIG_ENV=production
      - IDENTITY_URL=http://identity:8001
      - STORAGE_URL=http://storage:8002
    ports:
      - "8003:8003"
    depends_on:
      identity:
        condition: service_healthy
      storage:
        condition: service_healthy
    networks:
      - digidig-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8003/api/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  client:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER:-digidig}/digidig-client:${IMAGE_TAG:-latest}
    environment:
      - DIGIDIG_ENV=production
      - IDENTITY_URL=http://identity:8001
      - STORAGE_URL=http://storage:8002
      - SMTP_URL=http://smtp:8000
      - IMAP_URL=http://imap:8003
    ports:
      - "8004:8004"
    depends_on:
      identity:
        condition: service_healthy
      storage:
        condition: service_healthy
      smtp:
        condition: service_healthy
      imap:
        condition: service_healthy
    networks:
      - digidig-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8004/api/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  admin:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER:-digidig}/digidig-admin:${IMAGE_TAG:-latest}
    environment:
      - DIGIDIG_ENV=production
      - IDENTITY_URL=http://identity:8001
      - STORAGE_URL=http://storage:8002
    ports:
      - "8005:8005"
    depends_on:
      identity:
        condition: service_healthy
      storage:
        condition: service_healthy
    networks:
      - digidig-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8005/api/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  apidocs:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER:-digidig}/digidig-apidocs:${IMAGE_TAG:-latest}
    environment:
      - DIGIDIG_ENV=production
      - IDENTITY_URL=http://identity:8001
      - STORAGE_URL=http://storage:8002
      - SMTP_URL=http://smtp:8000
      - IMAP_URL=http://imap:8003
      - CLIENT_URL=http://client:8004
      - ADMIN_URL=http://admin:8005
    ports:
      - "8010:8010"
    depends_on:
      - identity
      - storage
      - smtp
      - imap
      - client
      - admin
    networks:
      - digidig-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8010/api/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

networks:
  digidig-net:
    driver: bridge

volumes:
  postgres_production_data:
    driver: local
  mongodb_production_data:
    driver: local