[project]
name = "digidig_mcp"
version = "0.1.0"
description = "A DIGiDIG MCP server for interacting with email services"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "mcp==1.4.1",
    "aiohttp>=3.8.0"
]

[project.optional-dependencies]
dev = ["debugpy==1.8.8"]