# Test Configuration Override
# Used by test container

database:
  postgres:
    host: postgres
  
  mongodb:
    host: mongo

services:
  identity:
    url: http://identity:8001
  smtp:
    rest_url: http://smtp:8000
  imap:
    rest_url: http://imap:8003
  storage:
    url: http://storage:8002

test:
  enabled: true
  skip_compose: true

logging:
  level: "DEBUG"
